name: Main file

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  call-workflow:
    uses: sanknoorsachin/exchange-rate-service/.github/workflows/test.yml@7cb5a94f577a303712f4cea64899af1f91134893
    with:
      
     secrets: inherit
